// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfbjpismsvqmihwisezv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmYmpwaXNtc3ZxbWlod2lzZXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDg1NjQsImV4cCI6MjA3MDkyNDU2NH0.CGo5d65BW28VS48Fp7qz5WJaselSC1NqQrF99z3Xyzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});